name: Deploy to AWS EC2

on:
  push:
    branches:
      - Deployment_Test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          source: "."
          target: "~/SmartCitywellness"

      - name: SSH into EC2 & deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            cd SmartCitywellness
            git pull origin Deployment_Test
            docker-compose down || true
            docker-compose up -d --build